spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/tasks
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

services:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8081/api/user-service}
