server:
  port: 8080

spring:
  application:
    name: task-service
  profiles:
    active: local

  liquibase:
    change-log: classpath:/db.changelog/changelog-master.yml

  jpa:
    hibernate:
      ddl-auto: validate
  mvc:
    servlet:
      path: /api/task-service

security:
  jwt:
    secret: 823740589273405892734058972340857203485702384720384702389475089133652358

